# Generated by Django 3.2.9 on 2021-11-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_alter_relatorio_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='faixa_idade',
            field=models.CharField(choices=[('ATÉ 9 ANOS', 'ATÉ 9 ANOS'), ('10 A 19', '10 A 19'), ('20 A 29', '20 A 29'), ('30 A 39', '30 A 39'), ('40 A 49', '40 A 49'), ('50 A 59', '50 A 59'), ('60 A 69', '60 A 69'), ('70 A 79', '70 A 79'), ('80 A 89', '80 A 89'), ('90 ANOS OU MAIS', '90 ANOS OU MAIS')], max_length=30, verbose_name='FAIXA DE IDADE'),
        ),
    ]
